apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - name: frontend-http
    port: 80
    targetPort: 80
